#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

export SOURCE_MODEL="${SOURCE_MODEL:-/mnt/data/checkpoints/usv_rl/fresh426_usv03_clear_short_probe.pt}"
export OUTPUT="${OUTPUT:-/mnt/data/checkpoints/usv_rl/fresh434_seed1461_agent23_late_clear_tracefit_from_fresh426.pt}"

export TRACE_JSONS="${TRACE_JSONS:-/tmp/fresh426_hard4_r3/repeat1_seed1461/seed1461.json}"
export ANCHOR_JSONS="${ANCHOR_JSONS:-/tmp/fresh426_hard4_r3/repeat1_seed1458/seed1458.json /tmp/fresh426_hard4_r3/repeat1_seed1460/seed1460.json /tmp/fresh426_hard4_r3/repeat1_seed1461/seed1461.json /tmp/fresh426_hard4_r3/repeat1_seed1463/seed1463.json}"
export PRESERVE_JSONS="${PRESERVE_JSONS:-/tmp/fresh426_hard4_r3/repeat1_seed1458/seed1458.json /tmp/fresh426_hard4_r3/repeat1_seed1460/seed1460.json /tmp/fresh426_hard4_r3/repeat1_seed1463/seed1463.json}"

export EPOCHS="${EPOCHS:-80}"
export LEARNING_RATE="${LEARNING_RATE:-1.0e-5}"
export ANCHOR_WEIGHT="${ANCHOR_WEIGHT:-280.0}"
export ANCHOR_BATCH_SIZE="${ANCHOR_BATCH_SIZE:-512}"
export MAX_GRAD_NORM="${MAX_GRAD_NORM:-0.050}"
export MIN_ERROR_NORM="${MIN_ERROR_NORM:-999.0}"
export TARGET_LINEAR_BLEND="${TARGET_LINEAR_BLEND:-0.75}"
export TARGET_OMEGA_BLEND="${TARGET_OMEGA_BLEND:-0.85}"

export PRESERVE_ACTION_WEIGHT="${PRESERVE_ACTION_WEIGHT:-12.0}"
export PRESERVE_MIN_TEAM_SEPARATION="${PRESERVE_MIN_TEAM_SEPARATION:-1.20}"

export LATE_CLEAR_WEIGHT="${LATE_CLEAR_WEIGHT:-4.8}"
export LATE_CLEAR_SOURCE_THRESHOLD="${LATE_CLEAR_SOURCE_THRESHOLD:-0.14}"
export LATE_CLEAR_TARGET_LINEAR="${LATE_CLEAR_TARGET_LINEAR:-0.18}"
export LATE_CLEAR_MIN_DISTANCE="${LATE_CLEAR_MIN_DISTANCE:-5.0}"
export LATE_CLEAR_MAX_CTE="${LATE_CLEAR_MAX_CTE:-2.40}"
export LATE_CLEAR_MIN_SEPARATION="${LATE_CLEAR_MIN_SEPARATION:-2.75}"
export LATE_CLEAR_MAX_THREAT="${LATE_CLEAR_MAX_THREAT:-0.08}"
export LATE_CLEAR_MIN_STEP="${LATE_CLEAR_MIN_STEP:-200}"
export LATE_CLEAR_CTE_OMEGA_BLEND="${LATE_CLEAR_CTE_OMEGA_BLEND:-0.70}"
export LATE_CLEAR_CTE_SLOW_THRESHOLD="${LATE_CLEAR_CTE_SLOW_THRESHOLD:-1.45}"
export LATE_CLEAR_CTE_RECOVERY_LINEAR="${LATE_CLEAR_CTE_RECOVERY_LINEAR:-0.12}"

export RECOVERY_SPEEDUP_WEIGHT="${RECOVERY_SPEEDUP_WEIGHT:-1.8}"
export RECOVERY_SPEEDUP_SOURCE_THRESHOLD="${RECOVERY_SPEEDUP_SOURCE_THRESHOLD:-0.13}"
export RECOVERY_SPEEDUP_TARGET_LINEAR="${RECOVERY_SPEEDUP_TARGET_LINEAR:-0.17}"
export RECOVERY_SPEEDUP_MIN_DISTANCE="${RECOVERY_SPEEDUP_MIN_DISTANCE:-5.0}"
export RECOVERY_SPEEDUP_MAX_CTE="${RECOVERY_SPEEDUP_MAX_CTE:-2.50}"
export RECOVERY_SPEEDUP_MIN_SEPARATION="${RECOVERY_SPEEDUP_MIN_SEPARATION:-2.75}"
export RECOVERY_SPEEDUP_MAX_THREAT="${RECOVERY_SPEEDUP_MAX_THREAT:-0.10}"
export RECOVERY_SPEEDUP_MIN_STEP="${RECOVERY_SPEEDUP_MIN_STEP:-200}"
export RECOVERY_SPEEDUP_MAX_ROUTE_PROGRESS="${RECOVERY_SPEEDUP_MAX_ROUTE_PROGRESS:-0.58}"
export RECOVERY_SPEEDUP_MAX_HEADING_ERROR="${RECOVERY_SPEEDUP_MAX_HEADING_ERROR:-2.50}"
export RECOVERY_SPEEDUP_CTE_OMEGA_BLEND="${RECOVERY_SPEEDUP_CTE_OMEGA_BLEND:-0.70}"

exec bash scripts/fit_fresh431_agent23_late_clear_trace.sh