#!/usr/bin/env bash
set -eo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

export OUTPUT="${OUTPUT:-/mnt/data/checkpoints/usv_rl/fresh436_usv02_stall_start_push_from_fresh432.pt}"
export EPOCHS="${EPOCHS:-120}"
export LEARNING_RATE="${LEARNING_RATE:-2.0e-5}"
export ANCHOR_WEIGHT="${ANCHOR_WEIGHT:-35.0}"
export PRESERVE_ACTION_WEIGHT="${PRESERVE_ACTION_WEIGHT:-6.0}"
export TARGET_LINEAR_BLEND="${TARGET_LINEAR_BLEND:-1.0}"
export TARGET_OMEGA_BLEND="${TARGET_OMEGA_BLEND:-0.70}"

export STALL_START_WEIGHT="${STALL_START_WEIGHT:-80.0}"
export STALL_START_TARGET_LINEAR="${STALL_START_TARGET_LINEAR:-0.18}"
export STALL_START_SOURCE_THRESHOLD="${STALL_START_SOURCE_THRESHOLD:-0.060}"
export STALL_START_MAX_ROUTE_PROGRESS="${STALL_START_MAX_ROUTE_PROGRESS:-0.030}"
export STALL_START_MAX_CTE="${STALL_START_MAX_CTE:-1.00}"
export STALL_START_HEADING_SLOW_THRESHOLD="${STALL_START_HEADING_SLOW_THRESHOLD:-2.45}"
export STALL_START_HEADING_RECOVERY_LINEAR="${STALL_START_HEADING_RECOVERY_LINEAR:-0.10}"

export GOAL_RETURN_WEIGHT="${GOAL_RETURN_WEIGHT:-0.0}"

exec bash scripts/fit_fresh435_stall_start_goal_return.sh